spring:
    datasource:
        url: jdbc:mysql://localhost:3306/test
        username: root
        password: root
        driverClassName: com.mysql.jdbc.Driver
        max-active : 20
        max-idle: 8
        min-idle: 8
        initial-size: 10

mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.tp.model

logging.level.com.spring.jiminshiro.mapper: debug